## 00: PyTorch Fundamentals

Resource notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/

If you have a question: https://github.com/mrdbourke/pytorch-deep-learning/discussions

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)

2.4.0+cu121


## Introduction to Tensors

### Creating Tensors

PyTorch tensors are created using `torch.Tensor()` = https://pytorch.org/docs/stable/tensors.html


In [2]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
# Get tensor back as a Python int
scalar.item()

7

In [5]:
#Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
#MATRIX
MATRIX = torch.tensor([[7,8],[9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX[0]

tensor([7, 8])

In [11]:
MATRIX[1]

tensor([ 9, 10])

In [12]:
MATRIX.shape

torch.Size([2, 2])

In [13]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],[3,6,9],[2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [14]:
TENSOR.ndim

3

In [15]:
TENSOR.shape

torch.Size([1, 3, 3])

In [16]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

### Random Tensors

Why random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers

Torch random tensors - https://pytorch.org/docs/stable/generated/torch.rand.html

In [17]:
# Create a random tensor of size (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.4202, 0.9599, 0.3580, 0.0899],
        [0.6392, 0.6924, 0.7817, 0.5458],
        [0.8813, 0.9881, 0.8377, 0.3131]])

In [18]:
random_tensor.ndim

2

In [19]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # height, width, colour channels (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [20]:
# Create a random tensor of my own size
second_random_tensor = torch.rand(6,4,5)
second_random_tensor

tensor([[[2.5947e-01, 7.3634e-01, 9.6674e-01, 9.3827e-01, 1.2436e-02],
         [6.8554e-01, 3.0612e-01, 2.7199e-01, 7.5993e-02, 2.7575e-01],
         [2.4495e-02, 7.9058e-01, 8.5103e-01, 9.8429e-01, 8.2580e-01],
         [3.5074e-01, 9.5646e-02, 8.5097e-01, 4.8943e-01, 2.6458e-01]],

        [[4.6469e-01, 8.9180e-01, 1.3293e-01, 5.8314e-03, 6.2699e-01],
         [1.2407e-01, 5.3179e-01, 5.4316e-01, 1.3541e-01, 5.3038e-01],
         [5.3735e-01, 4.8323e-01, 8.3099e-01, 3.6228e-01, 7.0809e-01],
         [1.5321e-01, 4.8560e-02, 9.0417e-02, 3.9326e-01, 6.3753e-01]],

        [[6.8175e-01, 7.3954e-01, 9.7156e-01, 5.5254e-01, 2.7211e-01],
         [2.0656e-01, 7.9371e-01, 2.3518e-01, 3.5661e-01, 7.4412e-01],
         [1.9197e-01, 3.7269e-01, 4.8531e-01, 5.9471e-01, 4.9227e-01],
         [2.6883e-03, 4.5231e-01, 6.2454e-01, 3.0947e-01, 2.2659e-01]],

        [[1.7236e-01, 4.7292e-01, 4.6946e-01, 1.6533e-01, 6.4462e-01],
         [7.3648e-01, 9.2950e-01, 9.9957e-01, 3.0236e-01, 9.6506e-01],


### Zeroes and Ones


In [21]:
#Create a tensor of all zeroes
zeroes = torch.zeros(size=(3,4))
zeroes

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [22]:
zeroes *random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [23]:
#Create a tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [24]:
ones.dtype

torch.float32

In [25]:
random_tensor.dtype

torch.float32

### Creating a range of tensors and tensor-like

In [26]:
#Use torch.range()
one_to_ten = torch.arange(start=1,end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [27]:
#Creating tensors like
ten_zeroes = torch.zeros_like(input=one_to_ten)
ten_zeroes

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

**Note:** Tensor datatypes is one of the 3 big errors you'll run into with PyTorch & deep learning:

1.Tensors not right datatype

2.Tensors not right shape

3.Tensors not on the right device


In [28]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, #What is the data type of the tensor (eg. float16 or float32)
                               device=None, #What device is your tensor is on
                               requires_grad=False) #whether or not to track gradients with this tensor's operations

float_32_tensor

tensor([3., 6., 9.])

In [29]:
float_32_tensor.dtype

torch.float32

In [30]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [31]:
float_16_tensor*float_32_tensor

tensor([ 9., 36., 81.])

In [32]:
int_32_tensor = torch.tensor([3,6,9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [33]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

In [34]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

### Getting information from tensors (tensor attributes)

1.Tensors not right datatype - to get the datatype from a tensor, we can use 'tensor.dtype'

2.Tensors not right shape - to get the shape from a tensor, we can use 'tensor.shape'  

3.Tensors not on the right device - to get device from a tensor, we can use 'tensor.device'

In [35]:
#Create a tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.4330, 0.6185, 0.2437, 0.2871],
        [0.5434, 0.8008, 0.6472, 0.4017],
        [0.0361, 0.0501, 0.0027, 0.1966]])

In [36]:
#Find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Which device the tensor is on: {some_tensor.device}")

tensor([[0.4330, 0.6185, 0.2437, 0.2871],
        [0.5434, 0.8008, 0.6472, 0.4017],
        [0.0361, 0.0501, 0.0027, 0.1966]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Which device the tensor is on: cpu


### Manipulating Tensors (tensor operations)

Tensor operations include:

*Addition

*Subtraction

*Multiplication (element-wise)

*Division

*Matrix multiplication

In [37]:
#Create a tensor and add 10 to it
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [38]:
#Multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [39]:
tensor

tensor([1, 2, 3])

In [40]:
#Subtract tensor by 10
tensor-10

tensor([-9, -8, -7])

In [41]:
#Try out PyTorch in-built functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [42]:
torch.add(tensor, 10)

tensor([11, 12, 13])

### Matrix multiplication

Two ways of performing multiplication in neural networks and deep learning:

1. Element-wise multiplication

2. Matrix multiplication (dot product)

There are two main rules that performing matrix multiplication needs to satisfy:
1. The **inner dimensions** must match:
*`(3,2) @ (3,2)` won't work

*`(2,3) @ (3,2)` will work

*`(3,2) @ (2,3)` will work

2. The resulting matrix has the shape of the outer dimensions:

*`(2,3) @ (3,2)` -> (2,2)

*`(3,2) @ (2,3)` -> (3,3)

In [43]:
#Element wise multiplication
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [44]:
#Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [45]:
tensor

tensor([1, 2, 3])

In [46]:
#Matrix multiplication by hand

1*1 + 2*2 + 3*3

14

In [47]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)


tensor(14)
CPU times: user 2.17 ms, sys: 0 ns, total: 2.17 ms
Wall time: 4.82 ms


In [48]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 1.41 ms, sys: 71 µs, total: 1.48 ms
Wall time: 1.88 ms


tensor(14)

###One of the most common errors in deep learning: shape errors


In [50]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])

tensor_B = torch.tensor([[7,10],
                        [8,11],
                        [9,12]])

torch.mm(tensor_A, tensor_B) ## torch.mm is the same as torch.matmul (it's an alias for writing less code)


RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [51]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix our tensor shape issues, we can manipulate the shape of one of our tensors using a transpose.
A transpose switches the axes or dimensions of a given tensor.

In [52]:
tensor_B, tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [53]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [54]:
# The matrix multiplication operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New shapes: tensor_A = {tensor_A.shape} (same shape as above), tensor_B.T = {tensor_B.T.shape}")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")


Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shapes: tensor_A = torch.Size([3, 2]) (same shape as above), tensor_B.T = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions must match
Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape: torch.Size([3, 3])


In [55]:
torch.matmul(tensor_A, tensor_B.T).shape

torch.Size([3, 3])

### Finding the min, max, mean, sum, etc(tensor aggregation)

In [56]:
# Create a tensor
x = torch.arange(0,100,10)
x, x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [57]:
# Find the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [58]:
#Find the max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [59]:
# Find the mean - note: the torch.mean() function requires a tensor of float32 datatype to work
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [60]:
# Find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

## Finding the positional min and max

In [61]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [62]:
#Find the position in the tensor that has the minimum value with argmin() -> returns index position of target tensor where the minimum value occurs
x.argmin()

tensor(0)

In [63]:
x[0]

tensor(0)

In [64]:
#Find the position in the tensor that has the maximum value with argmax()
x.argmax()

tensor(9)

In [65]:
x[9]

tensor(90)

## Reshaping, stacking, squeezing and unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of a certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - removes all `1` dimensions from a tensor
*Unsqueeze - add a `1` dimension to a target tensor
*Permute - Return a view of the input with dimensions permuted (swapped) in a certain way


In [66]:
#Create another tensor
import torch
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [67]:
# Add an extra dimension
x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [68]:
x_reshaped = x.reshape(9,1)
x_reshaped, x_reshaped.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [69]:
# Change the view
z = x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [70]:
# Changing z changes x (because a view of a tensor shares the same memory as the original input)
z[:,0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [71]:
# Stack tensors on top of each other
x_stacked = torch.stack([x,x,x,x], dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [72]:
x_stacked = torch.stack([x,x,x,x], dim=1)
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [73]:
# torch.squeeze() - removes all single dimensions from a target tensor
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimensions from X_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[5.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])
Previous shape: torch.Size([9, 1])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [74]:
x_reshaped.shape

torch.Size([9, 1])

In [75]:
x_reshaped.squeeze()

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [76]:
x_reshaped.squeeze().shape

torch.Size([9])

In [77]:
# torch.unsqueeze() - adds a single dimension to a target tensor at a specific dim(dimension)
print(f"Previous target: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

#Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


In [78]:
x_unsqueezed = x_squeezed.unsqueeze(dim=1)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")


New tensor: tensor([[5.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])
New shape: torch.Size([9, 1])


In [79]:
x_reshaped.squeeze()

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [80]:
# torch.permute() - rearranges the dimensions of a target tensor in a specified order
x_original = torch.rand(size=(224, 224, 3)) # [height, width, colour_channels]

#Permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2,0,1) # shifts axis 0->1, 1->2, 2->0
print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}") # [colour_channels, height, width]

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [81]:
x_original[0,0,0] = 72345
x_original[0,0,0],x_permuted[0,0,0]

(tensor(72345.), tensor(72345.))

## Indexing (selecting data from tensors)

Indexing with Pytorch is similar to indexing with NumPy.


In [82]:
# Create a tensor
import torch
x = torch.arange(1,10).reshape(1,3,3)
x,x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [83]:
# Let's index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [84]:
# Let's index on the middle bracket (dim=1)
x[0][0]

tensor([1, 2, 3])

In [85]:
# Let's index on the most inner bracket (last dimension)
x[0][0][0]

tensor(1)

In [86]:
x[0][2][2]

tensor(9)

In [87]:
# You can also use ":" to select "all" of a target dimension
x[:,0]

tensor([[1, 2, 3]])

In [88]:
# Get all values of 0th and 1st dimensions but only index 1 of 2nd dimension
x[:,:,1]

tensor([[2, 5, 8]])

In [89]:
# Get all values of the 0 dimension but only the 1 index value of 1st and 2nd dimension
x[:,1,1]

tensor([5])

In [90]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension
x[0,0,:]

tensor([1, 2, 3])

In [91]:
# Index on x to return 9
x[0,2,2]

tensor(9)

In [92]:
# Index on x to return 3, 6, 9
x[0,:,2]

tensor([3, 6, 9])

## PyTorch tensors & NumPy

NumPy is a popular scientific Python numerical computing library.

And because of this, PyTorch has functionality to interact with it.

* Data in NumPy, want in PyTorch tensor -> `torch.from_numpy(ndarray)`
*PyTorch tensor -> NumPy -> `torch.Tensor.numpy()`


In [93]:
# NumPy array to tensor
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array) # warning: when converting from numpy -> pytorch, pytorch reflects numpy's default datatype of float64 unless specified otherwise
array, tensor




(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [94]:
array.dtype

dtype('float64')

In [95]:
torch.arange(1.0, 8.0).dtype

torch.float32

In [96]:
#Change the value of the array, what will this do to the `tensor`?
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [97]:
# Tensor to NumPy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [98]:
# Change the tensor, what happens to `numpy_tensor`?
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility (trying to take random out of random)

In short how a neural network learns:

`start with random numbers -> tensor operations -> update random numbers to try and make them better representations of the data -> again -> again -> again...`

To reduce the randomness in neural networks and PyTorch comes the concept of a **random seed**.

Essentially what the random seed does is "flavour" the randomness.

In [99]:
import torch

#Create two random tensors
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.1462, 0.6156, 0.2212, 0.8795],
        [0.2061, 0.2523, 0.3284, 0.6753],
        [0.3384, 0.3972, 0.1405, 0.6466]])
tensor([[0.6353, 0.1671, 0.8245, 0.1643],
        [0.3487, 0.5096, 0.0647, 0.4787],
        [0.2184, 0.5276, 0.6050, 0.7956]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [100]:
# Let's make some random but reproducible tensors

import torch

# Set the random seed

RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running tensors and PyTorch objects on the GPUs (and making faster computations)

GPUs = faster computation on numbers, thanks to CUDA + NVIDIA hardware + PyTorch working behind the scenes to make everything awesome.

### 1. Getting a GPU

1. Easiest - Use Google Colab for a free GPU (options to upgrade as well)

2. Use your own GPU - takes a little bit of setup and requires the investment of purchasing a GPU, there is a lot of options... see this post for what option to get https://timdettmers.com/2023/01/30/which-gpu-for-deep-learning/

3. Use cloud computing - GCP, AWS, Azure, these services allow you to rent computers on the cloud and access them

For 2,3 PyTorch + GPU drivers (CUDA) takes a little bit of setting up, to do this, refer to PyTorch setup documentation: https://pytorch.org/get-started/locally/




In [5]:
!nvidia-smi

Wed Sep  4 06:32:33 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   56C    P8               9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

### 2. Check for GPU access with PyTorch

In [6]:
# Check for GPU access with PyTorch
import torch
torch.cuda.is_available()

True

For PyTorch since it's capable of running compute on the GPU or CPU, it's best practice to setup device agnostic code: https://pytorch.org/docs/stable/notes/cuda.html#best-practices

E.g. run on GPU if available, else default to CPU

In [7]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [8]:
# Count number of devices
torch.cuda.device_count()

1