## Exercises and Curriculum


In [1]:
import torch

1. Documentation reading - A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness). See the documentation on torch.Tensor and for torch.cuda.

https://pytorch.org/docs/stable/tensors.html#torch-tensor

https://pytorch.org/docs/main/notes/cuda.html#cuda-semantics

In [2]:
# 2 Create a random tensor with shape (7, 7).

tensor = torch.rand(7,7)
tensor

tensor([[0.2214, 0.1914, 0.7229, 0.1520, 0.4182, 0.3270, 0.1707],
        [0.3094, 0.0610, 0.5102, 0.4491, 0.3518, 0.0394, 0.3949],
        [0.3406, 0.7072, 0.3956, 0.0726, 0.1849, 0.6743, 0.0853],
        [0.8312, 0.8666, 0.2493, 0.0791, 0.6580, 0.3969, 0.3639],
        [0.2664, 0.7271, 0.3379, 0.0294, 0.7542, 0.5266, 0.1460],
        [0.7246, 0.3192, 0.5003, 0.1917, 0.2283, 0.9850, 0.2630],
        [0.8027, 0.2054, 0.9971, 0.7258, 0.8409, 0.2111, 0.9769]])

In [6]:
# 3 Perform a matrix multiplication on the tensor from 2 with another random tensor
# with shape (1, 7) (hint: you may have to transpose the second tensor).

tensor2 = torch.rand(1,7)

tensor2

tensor3 = torch.matmul(tensor, tensor2.T)

tensor2, tensor3, tensor3.shape

(tensor([[0.2623, 0.3441, 0.8963, 0.5447, 0.1092, 0.4552, 0.0410]]),
 tensor([[1.0562],
         [0.8766],
         [1.0574],
         [1.0502],
         [0.9671],
         [1.3369],
         [1.7983]]),
 torch.Size([7, 1]))

In [7]:
# 4 Set the random seed to 0 and do exercises 2 & 3 over again.

torch.manual_seed(0)

tensor = torch.rand(7,7)
tensor2 = torch.rand(1,7)

tensor3 = torch.matmul(tensor, tensor2.T)

tensor2, tensor3, tensor3.shape

(tensor([[0.4820, 0.8198, 0.9971, 0.6984, 0.5675, 0.8352, 0.2056]]),
 tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]),
 torch.Size([7, 1]))

In [8]:
# 5 Speaking of random seeds, we saw how to set it with torch.manual_seed()
# but is there a GPU equivalent?
# (hint: you'll need to look into the documentation for torch.cuda for this one).
# If there is, set the GPU random seed to 1234.

torch.cuda.manual_seed(1234)



In [9]:
# 6 Create two random tensors of shape (2, 3) and send them both
# to the GPU (you'll need access to a GPU for this).
# Set torch.manual_seed(1234) when creating the tensors
# (this doesn't have to be the GPU random seed).

torch.manual_seed(1234)

device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Device: {device}")

tensor = torch.rand(2,3).to(device)
tensor2 = torch.rand(2,3).to(device)
tensor, tensor2

Device: cpu


(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]]),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]]))

In [10]:
# 7 Perform a matrix multiplication on the tensors you created
# in 6 (again, you may have to adjust the shapes of one of the tensors).

tensor3 = torch.matmul(tensor, tensor2.T)
tensor3, tensor3.shape


(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]]),
 torch.Size([2, 2]))

In [11]:
# 8 Find the maximum and minimum values of the output of 7.

tensor3.max(), tensor3.min()

(tensor(0.5617), tensor(0.3647))

In [12]:
# 9 Find the maximum and minimum index values of the output of 7.

tensor3.argmax(), tensor3.argmin()

(tensor(3), tensor(0))

10. Make a random tensor with shape (1, 1, 1, 10) and then create a new tensor with all the 1 dimensions removed to be left with a tensor of shape (10). Set the seed to 7 when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

In [15]:
torch.manual_seed(7)

tensor = torch.rand(1,1,1,10)


tensor2 = tensor.squeeze()

tensor, tensor.shape, tensor2, tensor2.shape


(tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
            0.3653, 0.8513]]]]),
 torch.Size([1, 1, 1, 10]),
 tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
         0.8513]),
 torch.Size([10]))