## 00: PyTorch Fundamentals

Resource notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/

If you have a question: https://github.com/mrdbourke/pytorch-deep-learning/discussions

In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)

2.2.1+cu121


## Introduction to Tensors

### Creating Tensors

PyTorch tensors are created using `torch.Tensor()` = https://pytorch.org/docs/stable/tensors.html


In [3]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
# Get tensor back as a Python int
scalar.item()

7

In [6]:
#Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
#MATRIX
MATRIX = torch.tensor([[7,8],[9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
MATRIX.ndim

2

In [11]:
MATRIX[0]

tensor([7, 8])

In [12]:
MATRIX[1]

tensor([ 9, 10])

In [13]:
MATRIX.shape

torch.Size([2, 2])

In [14]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],[3,6,9],[2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [15]:
TENSOR.ndim

3

In [16]:
TENSOR.shape

torch.Size([1, 3, 3])

In [17]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

### Random Tensors

Why random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers

Torch random tensors - https://pytorch.org/docs/stable/generated/torch.rand.html

In [18]:
# Create a random tensor of size (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.0973, 0.1114, 0.0789, 0.6856],
        [0.1867, 0.9087, 0.8333, 0.7078],
        [0.0202, 0.9364, 0.0123, 0.0092]])

In [19]:
random_tensor.ndim

2

In [20]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # height, width, colour channels (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [21]:
# Create a random tensor of my own size
random_tensor = torch.rand(6,4,5)
random_tensor

tensor([[[0.2113, 0.5972, 0.1018, 0.6203, 0.5333],
         [0.3336, 0.2892, 0.1554, 0.4493, 0.9460],
         [0.5265, 0.4443, 0.6940, 0.1657, 0.2465],
         [0.0217, 0.5381, 0.2980, 0.9754, 0.5684]],

        [[0.6810, 0.8745, 0.5440, 0.5186, 0.0993],
         [0.3058, 0.4294, 0.2493, 0.0652, 0.9000],
         [0.8927, 0.3241, 0.8440, 0.9781, 0.9904],
         [0.2226, 0.4401, 0.0807, 0.6469, 0.8659]],

        [[0.1294, 0.2422, 0.0258, 0.6944, 0.0199],
         [0.8129, 0.0897, 0.9980, 0.6229, 0.0692],
         [0.4033, 0.3505, 0.0479, 0.9114, 0.5076],
         [0.1321, 0.7582, 0.1462, 0.5398, 0.6839]],

        [[0.4186, 0.3239, 0.5276, 0.1037, 0.9746],
         [0.5054, 0.3010, 0.8313, 0.2883, 0.6917],
         [0.0485, 0.4141, 0.4714, 0.7605, 0.4538],
         [0.4795, 0.9841, 0.5058, 0.4551, 0.8611]],

        [[0.5771, 0.3048, 0.4664, 0.0734, 0.7888],
         [0.5682, 0.7237, 0.9040, 0.8217, 0.0152],
         [0.2082, 0.8690, 0.5778, 0.6540, 0.0810],
         [0.9780, 0.928