## 00: PyTorch Fundamentals

Resource notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/

If you have a question: https://github.com/mrdbourke/pytorch-deep-learning/discussions

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)

2.3.0+cu121


## Introduction to Tensors

### Creating Tensors

PyTorch tensors are created using `torch.Tensor()` = https://pytorch.org/docs/stable/tensors.html


In [2]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
# Get tensor back as a Python int
scalar.item()

7

In [5]:
#Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
#MATRIX
MATRIX = torch.tensor([[7,8],[9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX[0]

tensor([7, 8])

In [11]:
MATRIX[1]

tensor([ 9, 10])

In [12]:
MATRIX.shape

torch.Size([2, 2])

In [13]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],[3,6,9],[2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [14]:
TENSOR.ndim

3

In [15]:
TENSOR.shape

torch.Size([1, 3, 3])

In [16]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

### Random Tensors

Why random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers

Torch random tensors - https://pytorch.org/docs/stable/generated/torch.rand.html

In [17]:
# Create a random tensor of size (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.2242, 0.8823, 0.7491, 0.8838],
        [0.4616, 0.1711, 0.6726, 0.3180],
        [0.2051, 0.2611, 0.9483, 0.0793]])

In [18]:
random_tensor.ndim

2

In [19]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # height, width, colour channels (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [20]:
# Create a random tensor of my own size
second_random_tensor = torch.rand(6,4,5)
second_random_tensor

tensor([[[0.8018, 0.0492, 0.1481, 0.8807, 0.0295],
         [0.1109, 0.2135, 0.4113, 0.4723, 0.6997],
         [0.5752, 0.0946, 0.2149, 0.7648, 0.3157],
         [0.3787, 0.5891, 0.7351, 0.5349, 0.8838]],

        [[0.9752, 0.7141, 0.3074, 0.7487, 0.9016],
         [0.8784, 0.6586, 0.3850, 0.5762, 0.4133],
         [0.2641, 0.5055, 0.7897, 0.6507, 0.8891],
         [0.1589, 0.0956, 0.6276, 0.2701, 0.7391]],

        [[0.3600, 0.8789, 0.0874, 0.2423, 0.7627],
         [0.4800, 0.2763, 0.0455, 0.7253, 0.5647],
         [0.8457, 0.6148, 0.2687, 0.7076, 0.5592],
         [0.3773, 0.2878, 0.2291, 0.1792, 0.8391]],

        [[0.1952, 0.6575, 0.6914, 0.3796, 0.5119],
         [0.6956, 0.6631, 0.0029, 0.3454, 0.1238],
         [0.0987, 0.5873, 0.2185, 0.0412, 0.9023],
         [0.7074, 0.3698, 0.5419, 0.4212, 0.4323]],

        [[0.2906, 0.3854, 0.9450, 0.2477, 0.3709],
         [0.5316, 0.7414, 0.2660, 0.6536, 0.1194],
         [0.3276, 0.8598, 0.8671, 0.0086, 0.9722],
         [0.0084, 0.372

### Zeroes and Ones


In [21]:
#Create a tensor of all zeroes
zeroes = torch.zeros(size=(3,4))
zeroes

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [22]:
zeroes *random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [23]:
#Create a tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [24]:
ones.dtype

torch.float32

In [25]:
random_tensor.dtype

torch.float32

### Creating a range of tensors and tensor-like

In [26]:
#Use torch.range()
one_to_ten = torch.arange(start=1,end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [27]:
#Creating tensors like
ten_zeroes = torch.zeros_like(input=one_to_ten)
ten_zeroes

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

**Note:** Tensor datatypes is one of the 3 big errors you'll run into with PyTorch & deep learning:

1.Tensors not right datatype

2.Tensors not right shape

3.Tensors not on the right device


In [28]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, #What is the data type of the tensor (eg. float16 or float32)
                               device=None, #What device is your tensor is on
                               requires_grad=False) #whether or not to track gradients with this tensor's operations

float_32_tensor

tensor([3., 6., 9.])

In [29]:
float_32_tensor.dtype

torch.float32

In [30]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [31]:
float_16_tensor*float_32_tensor

tensor([ 9., 36., 81.])

In [32]:
int_32_tensor = torch.tensor([3,6,9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [33]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

In [34]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

### Getting information from tensors (tensor attributes)

1.Tensors not right datatype - to get the datatype from a tensor, we can use 'tensor.dtype'

2.Tensors not right shape - to get the shape from a tensor, we can use 'tensor.shape'  

3.Tensors not on the right device - to get device from a tensor, we can use 'tensor.device'

In [35]:
#Create a tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.8706, 0.8823, 0.0875, 0.8756],
        [0.5223, 0.8010, 0.1804, 0.1712],
        [0.4214, 0.3464, 0.5968, 0.1211]])

In [36]:
#Find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Which device the tensor is on: {some_tensor.device}")

tensor([[0.8706, 0.8823, 0.0875, 0.8756],
        [0.5223, 0.8010, 0.1804, 0.1712],
        [0.4214, 0.3464, 0.5968, 0.1211]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Which device the tensor is on: cpu


### Manipulating Tensors (tensor operations)

Tensor operations include:

*Addition

*Subtraction

*Multiplication (element-wise)

*Division

*Matrix multiplication

In [37]:
#Create a tensor and add 10 to it
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [38]:
#Multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [39]:
tensor

tensor([1, 2, 3])

In [40]:
#Subtract tensor by 10
tensor-10

tensor([-9, -8, -7])

In [41]:
#Try out PyTorch in-built functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [42]:
torch.add(tensor, 10)

tensor([11, 12, 13])

### Matrix multiplication

Two ways of performing multiplication in neural networks and deep learning:

1. Element-wise multiplication

2. Matrix multiplication (dot product)

There are two main rules that performing matrix multiplication needs to satisfy:
1. The **inner dimensions** must match:
*`(3,2) @ (3,2)` won't work

*`(2,3) @ (3,2)` will work

*`(3,2) @ (2,3)` will work

2. The resulting matrix has the shape of the outer dimensions:

*`(2,3) @ (3,2)` -> (2,2)

*`(3,2) @ (2,3)` -> (3,3)

In [43]:
#Element wise multiplication
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [44]:
#Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [45]:
tensor

tensor([1, 2, 3])

In [46]:
#Matrix multiplication by hand

1*1 + 2*2 + 3*3

14

In [47]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)


tensor(14)
CPU times: user 1.25 ms, sys: 865 µs, total: 2.12 ms
Wall time: 7.53 ms


In [48]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 71 µs, sys: 11 µs, total: 82 µs
Wall time: 87 µs


tensor(14)

###One of the most common errors in deep learning: shape errors


In [50]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])

tensor_B = torch.tensor([[7,10],
                        [8,11],
                        [9,12]])

torch.mm(tensor_A, tensor_B) ## torch.mm is the same as torch.matmul (it's an alias for writing less code)


RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [51]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix our tensor shape issues, we can manipulate the shape of one of our tensors using a transpose.
A transpose switches the axes or dimensions of a given tensor.

In [55]:
tensor_B, tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [56]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [60]:
# The matrix multiplication operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New shapes: tensor_A = {tensor_A.shape} (same shape as above), tensor_B.T = {tensor_B.T.shape}")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")


Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shapes: tensor_A = torch.Size([3, 2]) (same shape as above), tensor_B.T = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions must match
Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape: torch.Size([3, 3])


In [58]:
torch.matmul(tensor_A, tensor_B.T).shape

torch.Size([3, 3])