## 00: PyTorch Fundamentals

Resource notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/

If you have a question: https://github.com/mrdbourke/pytorch-deep-learning/discussions

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)

2.3.0+cu121


## Introduction to Tensors

### Creating Tensors

PyTorch tensors are created using `torch.Tensor()` = https://pytorch.org/docs/stable/tensors.html


In [2]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
# Get tensor back as a Python int
scalar.item()

7

In [5]:
#Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
#MATRIX
MATRIX = torch.tensor([[7,8],[9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX[0]

tensor([7, 8])

In [11]:
MATRIX[1]

tensor([ 9, 10])

In [12]:
MATRIX.shape

torch.Size([2, 2])

In [13]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],[3,6,9],[2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [14]:
TENSOR.ndim

3

In [15]:
TENSOR.shape

torch.Size([1, 3, 3])

In [16]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

### Random Tensors

Why random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers

Torch random tensors - https://pytorch.org/docs/stable/generated/torch.rand.html

In [17]:
# Create a random tensor of size (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.6285, 0.4052, 0.2706, 0.1133],
        [0.5260, 0.0184, 0.7869, 0.7266],
        [0.3748, 0.9227, 0.8876, 0.2448]])

In [18]:
random_tensor.ndim

2

In [19]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # height, width, colour channels (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [20]:
# Create a random tensor of my own size
second_random_tensor = torch.rand(6,4,5)
second_random_tensor

tensor([[[0.1012, 0.9095, 0.3655, 0.7934, 0.1195],
         [0.7463, 0.5112, 0.5409, 0.8093, 0.2023],
         [0.6421, 0.7351, 0.8544, 0.6898, 0.6279],
         [0.1102, 0.6199, 0.3377, 0.6487, 0.7370]],

        [[0.9926, 0.2187, 0.3290, 0.5950, 0.1503],
         [0.3598, 0.7569, 0.6223, 0.1970, 0.9406],
         [0.3225, 0.6293, 0.7224, 0.7392, 0.1037],
         [0.8848, 0.7407, 0.2213, 0.8067, 0.5391]],

        [[0.1314, 0.5463, 0.4826, 0.3954, 0.7450],
         [0.6727, 0.9022, 0.9905, 0.5538, 0.5726],
         [0.9554, 0.0683, 0.2391, 0.5764, 0.4246],
         [0.1391, 0.8433, 0.6615, 0.1456, 0.1106]],

        [[0.8437, 0.1717, 0.9571, 0.5835, 0.2746],
         [0.9495, 0.3718, 0.3263, 0.0745, 0.1045],
         [0.8325, 0.7243, 0.8315, 0.6028, 0.2445],
         [0.3829, 0.4405, 0.3444, 0.2218, 0.8226]],

        [[0.9369, 0.2041, 0.1209, 0.8621, 0.4352],
         [0.0040, 0.8271, 0.2307, 0.2760, 0.5729],
         [0.3089, 0.3964, 0.5207, 0.7106, 0.9101],
         [0.8201, 0.928

### Zeroes and Ones


In [21]:
#Create a tensor of all zeroes
zeroes = torch.zeros(size=(3,4))
zeroes

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [22]:
zeroes *random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [23]:
#Create a tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [24]:
ones.dtype

torch.float32

In [25]:
random_tensor.dtype

torch.float32

### Creating a range of tensors and tensor-like

In [26]:
#Use torch.range()
one_to_ten = torch.arange(start=1,end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [27]:
#Creating tensors like
ten_zeroes = torch.zeros_like(input=one_to_ten)
ten_zeroes

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

**Note:** Tensor datatypes is one of the 3 big errors you'll run into with PyTorch & deep learning:

1.Tensors not right datatype

2.Tensors not right shape

3.Tensors not on the right device


In [28]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, #What is the data type of the tensor (eg. float16 or float32)
                               device=None, #What device is your tensor is on
                               requires_grad=False) #whether or not to track gradients with this tensor's operations

float_32_tensor

tensor([3., 6., 9.])

In [29]:
float_32_tensor.dtype

torch.float32

In [30]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [31]:
float_16_tensor*float_32_tensor

tensor([ 9., 36., 81.])

In [32]:
int_32_tensor = torch.tensor([3,6,9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [33]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

In [34]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

### Getting information from tensors (tensor attributes)

1.Tensors not right datatype - to get the datatype from a tensor, we can use 'tensor.dtype'

2.Tensors not right shape - to get the shape from a tensor, we can use 'tensor.shape'  

3.Tensors not on the right device - to get device from a tensor, we can use 'tensor.device'

In [35]:
#Create a tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.5275, 0.2525, 0.6723, 0.8598],
        [0.9555, 0.6079, 0.2447, 0.3279],
        [0.8189, 0.0821, 0.0952, 0.6102]])

In [36]:
#Find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Which device the tensor is on: {some_tensor.device}")

tensor([[0.5275, 0.2525, 0.6723, 0.8598],
        [0.9555, 0.6079, 0.2447, 0.3279],
        [0.8189, 0.0821, 0.0952, 0.6102]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Which device the tensor is on: cpu


### Manipulating Tensors (tensor operations)

Tensor operations include:

*Addition

*Subtraction

*Multiplication (element-wise)

*Division

*Matrix multiplication

In [37]:
#Create a tensor and add 10 to it
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [38]:
#Multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [39]:
tensor

tensor([1, 2, 3])

In [40]:
#Subtract tensor by 10
tensor-10

tensor([-9, -8, -7])

In [41]:
#Try out PyTorch in-built functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [42]:
torch.add(tensor, 10)

tensor([11, 12, 13])

### Matrix multiplication

Two ways of performing multiplication in neural networks and deep learning:

1. Element-wise multiplication

2. Matrix multiplication (dot product)

There are two main rules that performing matrix multiplication needs to satisfy:
1. The **inner dimensions** must match:
*`(3,2) @ (3,2)` won't work

*`(2,3) @ (3,2)` will work

*`(3,2) @ (2,3)` will work

2. The resulting matrix has the shape of the outer dimensions:

*`(2,3) @ (3,2)` -> (2,2)

*`(3,2) @ (2,3)` -> (3,3)

In [43]:
#Element wise multiplication
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [44]:
#Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [45]:
tensor

tensor([1, 2, 3])

In [46]:
#Matrix multiplication by hand

1*1 + 2*2 + 3*3

14

In [47]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)


tensor(14)
CPU times: user 2.41 ms, sys: 79 µs, total: 2.49 ms
Wall time: 19.2 ms


In [48]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 92 µs, sys: 16 µs, total: 108 µs
Wall time: 114 µs


tensor(14)

###One of the most common errors in deep learning: shape errors


In [49]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])

tensor_B = torch.tensor([[7,10],
                        [8,11],
                        [9,12]])

torch.mm(tensor_A, tensor_B) ## torch.mm is the same as torch.matmul (it's an alias for writing less code)


RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [50]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix our tensor shape issues, we can manipulate the shape of one of our tensors using a transpose.
A transpose switches the axes or dimensions of a given tensor.

In [51]:
tensor_B, tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [52]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [53]:
# The matrix multiplication operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New shapes: tensor_A = {tensor_A.shape} (same shape as above), tensor_B.T = {tensor_B.T.shape}")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")


Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shapes: tensor_A = torch.Size([3, 2]) (same shape as above), tensor_B.T = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions must match
Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape: torch.Size([3, 3])


In [54]:
torch.matmul(tensor_A, tensor_B.T).shape

torch.Size([3, 3])

### Finding the min, max, mean, sum, etc(tensor aggregation)

In [59]:
# Create a tensor
x = torch.arange(0,100,10)
x, x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [57]:
# Find the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [58]:
#Find the max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [61]:
# Find the mean - note: the torch.mean() function requires a tensor of float32 datatype to work
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [62]:
# Find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

## Finding the positional min and max

In [63]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [64]:
#Find the position in the tensor that has the minimum value with argmin() -> returns index position of target tensor where the minimum value occurs
x.argmin()

tensor(0)

In [65]:
x[0]

tensor(0)

In [66]:
#Find the position in the tensor that has the maximum value with argmax()
x.argmax()

tensor(9)

In [67]:
x[9]

tensor(90)

## Reshaping, stacking, squeezing and unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of a certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - removes all `1` dimensions from a tensor
*Unsqueeze - add a `1` dimension to a target tensor
*Permute - Return a view of the input with dimensions permuted (swapped) in a certain way


In [79]:
#Create another tensor
import torch
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [80]:
# Add an extra dimension
x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [81]:
x_reshaped = x.reshape(9,1)
x_reshaped, x_reshaped.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [82]:
# Change the view
z = x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [83]:
# Changing z changes x (because a view of a tensor shares the same memory as the original input)
z[:,0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [84]:
# Stack tensors on top of each other
x_stacked = torch.stack([x,x,x,x], dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [85]:
x_stacked = torch.stack([x,x,x,x], dim=1)
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [90]:
# torch.squeeze() - removes all single dimensions from a target tensor
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimensions from X_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[5.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])
Previous shape: torch.Size([9, 1])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [87]:
x_reshaped.shape

torch.Size([9, 1])

In [91]:
x_reshaped.squeeze()

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [92]:
x_reshaped.squeeze().shape

torch.Size([9])

In [93]:
# torch.unsqueeze() - adds a single dimension to a target tensor at a specific dim(dimension)
print(f"Previous target: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

#Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


In [94]:
x_unsqueezed = x_squeezed.unsqueeze(dim=1)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")


New tensor: tensor([[5.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])
New shape: torch.Size([9, 1])


In [95]:
x_reshaped.squeeze()

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [98]:
# torch.permute() - rearranges the dimensions of a target tensor in a specified order
x_original = torch.rand(size=(224, 224, 3)) # [height, width, colour_channels]

#Permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2,0,1) # shifts axis 0->1, 1->2, 2->0
print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}") # [colour_channels, height, width]

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [100]:
x_original[0,0,0] = 72345
x_original[0,0,0],x_permuted[0,0,0]

(tensor(72345.), tensor(72345.))